In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
data = pd.read_excel("WomensHundred_Dummy.xlsx")
data.head()

,Competition,MatchID,Date,Innings,Over,Ball,BatterID,BowlerID,Extra,Runs,Wicket,PitchX,PitchY,ReleaseY,ReleaseZ,PastY,PastZ,Bowler Type,Speed
0,The Hundred - Women's,HND_0001,2022-08-11,1,1,1,BAT_0001,BWL_0001,NaN,0,NaN,4.149,0.238,-0.080,1.756,0.407,1.004,ROB,52.896
1,The Hundred - Women's,HND_0001,2022-08-11,1,1,2,BAT_0001,BWL_0001,NaN,6,NaN,5.525,-0.087,0.174,2.076,-0.189,0.604,ROB,66.332
2,The Hundred - Women's,HND_0001,2022-08-11,1,1,3,BAT_0001,BWL_0001,NaN,0,NaN,4.211,0.017,-0.497,1.657,0.558,1.184,ROB,58.901
3,The Hundred - Women's,HND_0001,2022-08-11,1,1,4,BAT_0001,BWL_0001,NaN,4,NaN,1.563,-0.710,0.703,2.027,0.271,0.345,ROB,59.527
4,The Hundred - Women's,HND_0001,2022-08-11,1,1,5,BAT_0001,BWL_0001,NaN,4,NaN,10.925,-0.628,0.412,1.670,-0.802,0.216,ROB,47.294

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24117 entries, 0 to 24116
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  24117 non-null  object
 1   MatchID      24117 non-null  object
 2   Date         24117 non-null  datetime64[ns]
 3   Innings      24117 non-null  int64
 4   Over         24117 non-null  int64
 5   Ball         24117 non-null  int64
 6   BatterID     24117 non-null  object
 7   BowlerID     24117 non-null  object
 8   Extra        1168 non-null   object
 9   Runs         24117 non-null  int64
 10  Wicket       1436 non-null   object
 11  PitchX       24117 non-null  float64
 12  PitchY       24117 non-null  float64
 13  ReleaseY     24117 non-null  float64
 14  ReleaseZ     24117 non-null  float64
 15  PastY        24117 non-null  float64
 16  PastZ        24117 non-null  float64
 17  Bowler Type  24117 non-null  object
 18  Speed        24117 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(4), object(7)
memory usage: 3.5+ MB

### Splitting data : Pace & Spin

In [5]:
df = data[["Date", "BatterID", "BowlerID", "PitchX", "PitchY", "ReleaseY", "ReleaseZ", "PastY", "PastZ", "Bowler Type", "Runs"]].copy()
df_pace = df[df["Bowler Type"].str.endswith(('M', 'F'))].copy()
df_spin = df[df["Bowler Type"].str.endswith(('B'))].copy()

In [6]:
features = ["PitchX","PitchY","ReleaseY", "ReleaseZ", "PastY", "PastZ"]

### OLS Regression for Pace Data

In [7]:
Y_pace = df_pace["Runs"]
X_pace = sm.add_constant(df_pace[features])
res_pace = sm.OLS(Y_pace, X_pace).fit()
res_pace.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Runs   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.623
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.136
Time:                        00:17:37   Log-Likelihood:                -22141.
No. Observations:               12184   AIC:                         4.430e+04
Df Residuals:                   12177   BIC:                         4.435e+04
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9700      0.161      6.024      0.000       0.654       1.286
PitchX         0.0027      0.004      0.717      0.473      -0.005       0.010
PitchY         0.0091      0.032      0.285      0.776      -0.053       0.072
ReleaseY      -0.0075      0.022     -0.346      0.729      -0.050       0.035
ReleaseZ       0.0593      0.082      0.727      0.467      -0.101       0.219
PastY          0.0573      0.026      2.187      0.029       0.006       0.109
PastZ          0.0706      0.036      1.974      0.048       0.000       0.141
==============================================================================
Omnibus:                     2526.683   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4397.444
Skew:                           1.396   Prob(JB):                         0.00
Kurtosis:                       3.933   Cond. No.                         101.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### OLS Regression For Spin Data

In [8]:
Y_spin = df_spin["Runs"]
X_spin = sm.add_constant(df_spin[features])
res_spin = sm.OLS(Y_spin, X_spin).fit()
res_spin.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Runs   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.9159
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.482
Time:                        00:18:14   Log-Likelihood:                -21207.
No. Observations:               11933   AIC:                         4.243e+04
Df Residuals:                   11926   BIC:                         4.248e+04
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.1782      0.156      7.564      0.000       0.873       1.484
PitchX        -0.0027      0.004     -0.731      0.465      -0.010       0.005
PitchY        -0.0192      0.031     -0.621      0.534      -0.080       0.041
ReleaseY      -0.0395      0.021     -1.883      0.060      -0.081       0.002
ReleaseZ       0.0175      0.079      0.222      0.825      -0.137       0.172
PastY          0.0246      0.026      0.961      0.337      -0.026       0.075
PastZ         -0.0132      0.034     -0.384      0.701      -0.081       0.054
==============================================================================
Omnibus:                     2972.064   Durbin-Watson:                   1.946
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5911.910
Skew:                           1.526   Prob(JB):                         0.00
Kurtosis:                       4.604   Cond. No.                         101.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
df_pace["expected_runs"] = res_pace.predict(X_pace)
df_pace["residual"] = df_pace["Runs"] - df_pace["expected_runs"]

### Aggregation For Pace Batters

In [10]:
pace_batters = (
    df_pace
    .groupby("BatterID")
    .agg(
        n_balls=("Runs", "size"),
        mean_residual=("residual", "mean"),
        std_residual=("residual", "std")
    )
)
# se is "Standart Error"
pace_batters["se"] = pace_batters["std_residual"] / pace_batters["n_balls"]**0.5
pace_batters["t_stat"] = pace_batters["mean_residual"] / pace_batters["se"]

# -----------------------------------------------------

In [11]:
df_spin["expected_runs"] = res_spin.predict(X_spin)
df_spin["residual"] = df_spin["Runs"] - df_spin["expected_runs"]

### Aggregation For Spin Batters

In [12]:
spin_batters = (
    df_spin
    .groupby("BatterID")
    .agg(
        n_balls=("Runs", "size"),
        mean_residual=("residual", "mean"),
        std_residual=("residual", "std")
    )
    .dropna()
)

In [13]:
spin_batters["se"] = spin_batters["std_residual"] / (spin_batters["n_balls"] ** 0.5)
spin_batters["t_stat"] = spin_batters["mean_residual"] / spin_batters["se"]

In [14]:
spin_batters.sort_values("t_stat", ascending=False).head(10)

          n_balls  mean_residual  std_residual        se    t_stat
BatterID
BAT_0017      334       0.335702      1.660108  0.090837  3.695650
BAT_0066      351       0.247387      1.499080  0.080015  3.091761
BAT_0113       85       0.555200      1.923708  0.208655  2.660849
BAT_0022      191       0.321965      1.788363  0.129401  2.488106
BAT_0104      291       0.227391      1.645037  0.096434  2.357999
BAT_0043      211       0.257095      1.643980  0.113176  2.271635
BAT_0114      160       0.255207      1.490072  0.117801  2.166433
BAT_0002       73       0.362347      1.509889  0.176719  2.050411
BAT_0105       20       0.914032      2.034994  0.455039  2.008692
BAT_0077       91       0.221616      1.433891  0.150313  1.474366

In [15]:
pace_batters.sort_values("t_stat", ascending=False).head(10)

          n_balls  mean_residual  std_residual        se    t_stat
BatterID
BAT_0066      372       0.195639      1.579432  0.081890  2.389059
BAT_0001       46       0.633451      1.848858  0.272599  2.323746
BAT_0123       13       1.240088      1.967438  0.545669  2.272601
BAT_0113      121       0.337778      1.694350  0.154032  2.192913
BAT_0031      125       0.352257      1.803858  0.161342  2.183293
BAT_0108      136       0.300847      1.712553  0.146850  2.048664
BAT_0073       14       0.864591      1.655187  0.442367  1.954464
BAT_0016      208       0.217132      1.654066  0.114689  1.893227
BAT_0132      123       0.262638      1.570052  0.141567  1.855223
BAT_0062       97       0.312698      1.703446  0.172959  1.807936